apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer    # set the type of Service
  selector:
    app: backend      # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend      # needs to be the same as Service's selector
spec:
  containers:
  - name: backend
    image: jackmqa/pet-backend:latest
    ports:
    - containerPort: 9966
